#!/bin/bash
HEIGHT=18
CHOICE_HEIGHT=10
WIDTH=50
HWADDR=`ifconfig eth0 | grep HW | awk ' BEGIN { FS = " " } ; { print $5 } ; '`
IPADDR=`ifconfig eth0 | grep "inet addr:" | awk $'{print $2}' | cut -d ":" -f 2`
MASK=`ifconfig eth0 | grep "Mask:" | awk $'{print $2}' | cut -d ":" -f 2`
GW=`ip route list | grep default | awk $'{print $3}'`

#questo ci serve per un controllo sugli ip inseriti
octet="(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])"
ip4="^$octet\\.$octet\\.$octet\\.$octet$"

dns_file="/etc/resolv.conf"
interfaces_file="/etc/network/interfaces"

OPTIONS=(
Network/IP   "IP Settings        "
Timezone     "Set Time Zone      "
Reboot       "Reboot the System  "
Shell        "Exit to Shell      "
)

show_current_info(){
      if (whiptail --backtitle "JBL Network Setup" --title "Current Setting" \
                --yesno "\n\n IP Address:   $IPADDR \n\n Default gateway:   $GW\n\n Subnet mask:   $MASK \n\n\n   Do you want to change it?" \
                --defaultno  $HEIGHT $WIDTH 3>&1 1>&2 2>&3)
        then
	   ip_sub_menu
        else
      	   break
      fi

}

set_ip(){
    echo "# interfaces(5) file used by ifup(8) and ifdown(8)" > $interfaces_file
    echo ""  >> $interfaces_file
    echo "# Please note that this file is written to be used with dhcpcd" >> $interfaces_file
    echo "# For static IP, consult /etc/dhcpcd.conf and 'man dhcpcd.conf'" >> $interfaces_file
    echo ""  >> $interfaces_file
    echo "# Include files from /etc/network/interfaces.d:" >> $interfaces_file
    echo "# source-directory /etc/network/interfaces.d" >> $interfaces_file
    echo "auto lo" >> $interfaces_file
    echo "iface lo inet loopback" >> $interfaces_file
    echo ""  >> $interfaces_file
    echo "auto eth0" >> $interfaces_file
    echo "iface eth0 inet static" >> $interfaces_file
    echo "  address $1" >> $interfaces_file
    echo "  netmask $2" >> $interfaces_file
    echo "  gateway $3" >> $interfaces_file
    echo "" >> $interfaces_file
    echo "#allow-hotplug wlan0" >> $interfaces_file
    echo "#iface wlan0 inet manual" >> $interfaces_file
    echo "#    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf" >> $interfaces_file
    echo "" >> $interfaces_file
    echo "#allow-hotplug wlan1" >> $interfaces_file
    echo "#iface wlan1 inet manual" >> $interfaces_file
    echo "#    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf  " >> $interfaces_file
}

set_dns(){
    echo "# Generated by resolvconf" > $dns_file
    echo "nameserver $1" >> $dns_file
}

ip_sub_menu(){
while [ -z $result ] || [ $result == "1" ];
     do

        while [[ -z $ip_result ]] || [[ $ip_result == "1" ]] ; do
            ipaddr=$(whiptail --backtitle "JBL Network Setup" --inputbox "IP Address" $HEIGHT $WIDTH  3>&1 1>&2 2>&3)
            if ! [[ $ipaddr =~ $ip4 ]]; then
                whiptail --msgbox "Invalid IP!" 10 60
                ! true
            fi
            ip_result=$?
        done
        while [[ -z $sm_result ]] || [[ $sm_result == "1" ]] ; do
            netmask=$(whiptail --backtitle "JBL Network Setup" --inputbox "Subnet Mask" $HEIGHT $WIDTH  3>&1 1>&2 2>&3)
            if ! [[ $netmask =~ $ip4 ]]; then
                whiptail --msgbox "Invalid Netmask!" 10 60
                ! true
            fi
            sm_result=$?
        done
        while [[ -z $gw_result ]] || [[ $gw_result == "1" ]] ; do
            gateway=$(whiptail --backtitle "JBL Network Setup" --inputbox "Default Gateway" $HEIGHT $WIDTH  3>&1 1>&2 2>&3)
            if ! [[ $gateway =~ $ip4 ]]; then
                whiptail --msgbox "Invalid Default Gateway!" 10 60
                ! true
            fi
            gw_result=$?
        done
        while [[ -z $dns_result ]] || [[ $dns_result == "1" ]] ; do
            dns1=$(whiptail --backtitle "JBL Network Setup" --inputbox "Primary DNS" $HEIGHT $WIDTH  3>&1 1>&2 2>&3)
            if ! [[ $dns1 =~ $ip4 ]]; then
                whiptail --msgbox "Invalid DNS!" 10 60
                ! true
            fi
            dns_result=$?
        done
        whiptail --backtitle "JBL Network Setup" --title "Are the settings correct?" --yesno "\n IP Adress: $ipaddr \n Netmask: $netmask \n Gateway: $gateway \n DNS: $dns1 \n" $HEIGHT $WIDTH 3>&1 1>&2 2>&3
        result=$?
    done
    set_dns $dns1
    set_ip $ipaddr $netmask $gateway
    if [ $? == "1" ]
	then
		whiptail --backtitle "JBL Network Setup" --title "ERROR!" --msgbox "Settings are NOT written to /etc/network/interfaces and/etc/resolv.conf, be sure that you are root!" $HEIGHT $WIDTH
	else
		whiptail --backtitle "JBL Network Setup" --title "OK!" --msgbox "New settings are written to config file, please reboot to apply" $HEIGHT $WIDTH

    fi
#reset variabili per far ripartire il loop in caso si rientri nel menu
result="1"
ip_result="1"
sm_result="1"
gw_result="1"
dns_result="1"
}


while true
do
CHOICE=$(whiptail --nocancel --clear \
    --backtitle "JBL Setup" \
    --title "JBL Setup" \
    --menu "Tasks: " \
    $HEIGHT $WIDTH $CHOICE_HEIGHT \
    "${OPTIONS[@]}" \
    2>&1 >/dev/tty)

clear
case $CHOICE in
    Network/IP)
        show_current_info
        ;;
    Timezone)
        dpkg-reconfigure tzdata
        ;;
    Reboot)
        systemctl reboot
        ;;
    Shell)
        exit
        ;;
esac
done
